buildscript {
    repositories {
        maven { url = 'https://files.minecraftforge.net/maven' }
        maven { url = "https://plugins.gradle.org/m2/" }
        maven { url = "https://maven.parchmentmc.org" }
        mavenCentral()
    }
    dependencies {
        classpath "org.apache.httpcomponents:httpmime:4.5.14"
        classpath "org.parchmentmc:librarian:1.+"
    }
}
plugins {
    id 'earth.terrarium.cloche' version '[0.10.0,0.11.0)'
}

apply plugin: "java"
apply plugin: 'eclipse'
apply plugin: 'maven-publish'

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    cloche.librariesMinecraft()

    mavenCentral()

    cloche {
        main()

        mavenFabric()
        mavenNeoforgedMeta()
        mavenNeoforged()
    }
}

cloche {
    forge("forge:1.12.2") {
        minecraftVersion = "1.12.2"
        loaderVersion = "14.23.5.2864"

        runs {
            server()
            client()
            data()
        }
    }
}



idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

